# kax_fish_biomass_props_for_bree.R
# 5 Sep 2018
# script to generate summaries of proportional contributions of key fish groups to total biomass caught in IYGPT/MIDOC trawls on k axis


library(tidyverse)

usr <- Sys.info()["user"]
d<- paste0("/Users/", usr, "/GitHub/K_axis_midoc/")
setwd(d)

fbm <- readRDS("./derived data/codend_fish_biomass.rds")

# total biomass and proportional biomass (tbm and pbm) columns in this df are across all taxa. We want totals for fish, then proportional contributions
# this will be the proportion of the total catch, across cod-ends 2:6 (ascending cod ends)
# proportions for individual cod-ends could be generated by modifying the group_by groupings

f.bmp <- fbm %>% filter(cod.end%in%as.character(c(2:6))) %>% select(-TL.mm, -FL.mm,-SL.mm, -photo, -photo.label, -notes, -to.check) %>%
		  group_by(midoc.stn) %>%
		  mutate(tbm = sum(wt.g, na.rm=T)) %>% ungroup() %>%
		  filter(fish.grp%in%c("Bathylagiids","Kreffichthys andersonii","Protomyctophum sp", "Electrona sp.","Gymnoscopelus sp.")) %>%
		  group_by(midoc.stn, fish.grp) %>%
		  mutate(bm.grp = sum(wt.g, na.rm=T)) %>% ungroup() %>%
		  mutate(pbm.grp = bm.grp/tbm) %>%
		  select(midoc.stn,date, fish.grp, tbm, bm.grp, pbm.grp) %>%
		  distinct()  

saveRDS(f.bmp, "./biomass summaries/fish_groups_biomass_proportions.RDS")
write_csv(f.bmp, "./biomass summaries/fish_groups_biomass_proportions.csv")